// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqzfjhtgutnzghymrqhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxemZqaHRndXRuemdoeW1ycWh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDY2MzEsImV4cCI6MjA3Mzc4MjYzMX0.8Gnaetyqc7SfY-LMGXS0ILZZMgUfFdbsbzx5h7lmbMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});